name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup Node
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '22.x'

    - name: Enable Corepack
      run: corepack enable

    - name: Enable Corepack
      run: corepack enable

    - name: Install dependencies
      run: yarn install

    - name: Lint
      run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup Node
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '22.x'

    - name: Enable Corepack
      run: corepack enable

    - name: Enable Corepack
      run: corepack enable

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
      
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 7
