name: Manual Release Prep

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v2.3.3)'
        required: true
        type: string

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: '22.x'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: npm ci

      - name: Rebuild Dist
        run: npm run build

      - name: Commit Dist and Tag
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # Force update dist in case it changed
          git add dist/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "Dist is already up to date."
          else
            git commit -m "chore: Update dist for release ${{ inputs.version }} [skip ci]"
            git push origin master
          fi

          # Create and Push Tag
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}
          
          echo "✅ Tag ${{ inputs.version }} push complete."

      - name: Get version without v
        id: get_version
        run: echo "VERSION=${{ inputs.version }}" | sed 's/v//' >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
          path: ./CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
          files: |
            dist/**/*
            LICENSE
            README.md
            action.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
