name: Update Dist

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master

jobs:
  update-dist:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            
            const matchArtifact = artifacts.data.artifacts.find(artifact => {
              return artifact.name == "dist"
            });
            
            if (!matchArtifact) {
              core.setFailed('No dist artifact found');
              return;
            }
            
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip'
            });
            
            const fs = require('fs');
            fs.writeFileSync('dist.zip', Buffer.from(download.data));
            
            console.log('Artifact downloaded');

      - name: Extract artifact
        run: |
          mkdir -p extracted
          unzip -o dist.zip -d extracted
          
          # Ensure dist directory exists
          mkdir -p dist
          
          # Copy the extracted files to dist directory
          cp -r extracted/* dist/
          
          echo "Artifact extracted and copied to dist directory"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git add dist/
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "chore: Update dist files from CI build [skip ci]"
          git push
          
          echo "Dist files updated successfully"

